### ISSUE TITLE
TypeError: average_precision_score() got an unexpected keyword argument 'pos_label'

### ISSUE THREAD

**Issue by PANXIONG-CN** [PhilipMay/mltb#11] opened 2019-07-03 08:44 UTC
I run your keras_demo.py, but have the error below:
I install the mltb by `pip install mltb`
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-fae66036345b> in <module>()
     28     class_weight={
     29         0: 1.0,
---> 30         1: 9.0
     31     },
     32 )

~/anaconda3/lib/python3.6/site-packages/keras/engine/training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, **kwargs)
   1037                                         initial_epoch=initial_epoch,
   1038                                         steps_per_epoch=steps_per_epoch,
-> 1039                                         validation_steps=validation_steps)
   1040 
   1041     def evaluate(self, x=None, y=None,

~/anaconda3/lib/python3.6/site-packages/keras/engine/training_arrays.py in fit_loop(model, f, ins, out_labels, batch_size, epochs, verbose, callbacks, val_f, val_ins, shuffle, callback_metrics, initial_epoch, steps_per_epoch, validation_steps)
    215                         for l, o in zip(out_labels, val_outs):
    216                             epoch_logs['val_' + l] = o
--> 217         callbacks.on_epoch_end(epoch, epoch_logs)
    218         if callback_model.stop_training:
    219             break

~/anaconda3/lib/python3.6/site-packages/keras/callbacks.py in on_epoch_end(self, epoch, logs)
     77         logs = logs or {}
     78         for callback in self.callbacks:
---> 79             callback.on_epoch_end(epoch, logs)
     80 
     81     def on_batch_begin(self, batch, logs=None):

~/anaconda3/lib/python3.6/site-packages/mltb/keras.py in on_epoch_end(self, batch, logs)
     35 
     36         average_precision = sklearn.metrics.average_precision_score(self.val_labels, predict_results,
---> 37                                                                     pos_label=self.pos_label)
     38         logs['average_precision'] = average_precision
     39 

TypeError: average_precision_score() got an unexpected keyword argument 'pos_label'

```

**Comment by PhilipMay** [comment] 2019-07-03 08:53
Thanks for the report - I will have a look into it.

**Comment by PhilipMay** [comment] 2019-07-03 19:51
Hi @PANXIONG-CN - the problem is that your sklearn package is too old.
Please try to update it with `pip install scikit-learn -U`.

In your sklearn version the keyword argument 'pos_label' was not implemented.

Can you please report back if your problem has been solved?

Thanks
Philip

**Comment by PANXIONG-CN** [comment] 2019-07-08 09:05
I fix it by above method, thanks.

**Comment by PhilipMay** [comment] 2019-07-08 09:09
Ok. :-)
So I close this.

**Closed as completed by PhilipMay** 2019-07-08 09:09 UTC
Labels: help wanted
